# Generated by Django 4.2.5 on 2023-10-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('verification_string', models.TextField(unique=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecNotes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notename', models.TextField()),
                ('content', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('username', models.TextField()),
                ('website', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('encrypted_file_name', models.TextField(null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('card_number', models.TextField()),
                ('card_type', models.TextField()),
                ('card_cvv', models.TextField()),
                ('card_exp', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
