# Generated by Django 4.2.4 on 2023-09-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardsdb_secnotesdb_delete_userdb_remove_passdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='secnotes',
            old_name='name',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='secnotes',
            old_name='notes',
            new_name='notename',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='files',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='secnotes',
            name='date_added',
        ),
        migrations.AddField(
            model_name='cards',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secnotes',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
