# Generated by Django 4.2.5 on 2023-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files_encrypted_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_cvv',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_exp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='encrypted_file_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pass',
            name='website',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secnotes',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secnotes',
            name='notename',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(),
        ),
    ]
