version: '3.9'

services:
  backend-db:
    image: postgres:latest
    container_name: backend-db
    environment:
      POSTGRES_USER: sujoy
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  backend-api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${API_PORT}:8000"
    depends_on:
      backend-db:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: